2021-02-18 23:56:51.165 CET [4408] LOG:  listening on IPv6 address "::1", port 5432
2021-02-18 23:56:51.166 CET [4408] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-02-18 23:56:51.215 CET [18412] LOG:  database system was shut down at 2021-02-18 23:56:47 CET
2021-02-18 23:56:51.263 CET [4408] LOG:  database system is ready to accept connections
2021-02-18 23:58:18.712 CET [12196] ERROR:  relation "test" does not exist at character 13
2021-02-18 23:58:18.712 CET [12196] STATEMENT:  INSERT INTO test VALUES(456,5)
2021-02-18 23:58:49.986 CET [18200] ERROR:  relation "test" does not exist at character 13
2021-02-18 23:58:49.986 CET [18200] STATEMENT:  INSERT INTO test VALUES(456,5)
2021-02-18 23:59:21.844 CET [18380] ERROR:  relation "test" does not exist at character 13
2021-02-18 23:59:21.844 CET [18380] STATEMENT:  INSERT INTO test VALUES(456,5)
2021-02-18 23:59:34.595 CET [19180] ERROR:  relation "test" does not exist at character 13
2021-02-18 23:59:34.595 CET [19180] STATEMENT:  INSERT INTO test VALUES(456,5)
2021-02-19 00:00:05.576 CET [22176] ERROR:  relation "test" does not exist at character 13
2021-02-19 00:00:05.576 CET [22176] STATEMENT:  INSERT INTO test VALUES(456,5)
2021-02-19 00:01:39.172 CET [5960] ERROR:  column "abc" does not exist at character 55
2021-02-19 00:01:39.172 CET [5960] STATEMENT:  INSERT INTO users (userid, login, password) VALUES (1,abc,abc);
2021-02-19 00:02:01.591 CET [2804] ERROR:  relation "test" does not exist at character 13
2021-02-19 00:02:01.591 CET [2804] STATEMENT:  INSERT INTO test VALUES(456,5)
2021-02-19 00:02:10.584 CET [9132] ERROR:  relation "test" does not exist at character 13
2021-02-19 00:02:10.584 CET [9132] STATEMENT:  INSERT INTO test VALUES(456,5)
2021-02-19 00:02:12.161 CET [9132] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-19 00:03:25.765 CET [1460] ERROR:  relation "test" does not exist at character 13
2021-02-19 00:03:25.765 CET [1460] STATEMENT:  INSERT INTO test VALUES(456,5)
2021-02-19 00:06:16.661 CET [9304] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-19 00:09:51.534 CET [22836] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-19 00:09:51.534 CET [22836] DETAIL:  Key (userid)=(0) already exists.
2021-02-19 00:09:51.534 CET [22836] STATEMENT:  INSERT INTO users (userid,login,password) VALUES(0,0,0)
2021-02-19 00:09:51.556 CET [22836] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-19 00:26:54.581 CET [11080] ERROR:  column "hello" does not exist at character 52
2021-02-19 00:26:54.581 CET [11080] STATEMENT:  INSERT INTO users (userid,login,password) VALUES(2,hello,nobo)
2021-02-19 00:27:29.644 CET [10476] ERROR:  column "hello" does not exist at character 52
2021-02-19 00:27:29.644 CET [10476] STATEMENT:  INSERT INTO users (userid,login,password) VALUES(2,hello,nobo)
2021-02-19 00:27:57.045 CET [5960] ERROR:  column "hello" does not exist at character 52
2021-02-19 00:27:57.045 CET [5960] STATEMENT:  INSERT INTO users (userid,login,password) VALUES(2,hello,nobo);
2021-02-19 00:32:11.914 CET [5960] ERROR:  character with byte sequence 0xef 0xbf 0xbd in encoding "UTF8" has no equivalent in encoding "WIN1250"
2021-02-19 00:32:11.914 CET [5960] STATEMENT:  SELECT * FROM users;
2021-02-19 00:32:43.783 CET [5960] ERROR:  character with byte sequence 0xef 0xbf 0xbd in encoding "UTF8" has no equivalent in encoding "WIN1250"
2021-02-19 00:32:43.783 CET [5960] STATEMENT:  SELECT * FROM users;
2021-02-19 00:36:17.657 CET [5960] ERROR:  column "username" of relation "users" does not exist at character 69
2021-02-19 00:36:17.657 CET [5960] STATEMENT:  PREPARE registration (int, text, text) AS INSERT INTO users (userid,username,password) VALUES ($1,$2,$3);
2021-02-19 00:37:00.463 CET [5960] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-19 00:37:00.463 CET [5960] DETAIL:  Key (userid)=(4) already exists.
2021-02-19 00:37:00.463 CET [5960] STATEMENT:  EXECUTE registration (4,'henlo','bob');
2021-02-19 00:44:54.359 CET [13000] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-19 00:45:00.585 CET [12656] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-19 00:45:07.578 CET [12516] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-19 00:47:53.733 CET [4408] LOG:  server process (PID 5960) was terminated by exception 0xC000013A
2021-02-19 00:47:53.733 CET [4408] DETAIL:  Failed process was running: SELECT * FROM users;
2021-02-19 00:47:53.733 CET [4408] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-02-19 00:47:53.734 CET [4408] LOG:  terminating any other active server processes
2021-02-19 00:47:53.736 CET [19812] WARNING:  terminating connection because of crash of another server process
2021-02-19 00:47:53.736 CET [19812] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-02-19 00:47:53.736 CET [19812] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-02-19 00:47:53.765 CET [4408] LOG:  statistics collector process (PID 13224) was terminated by exception 0xC000013A
2021-02-19 00:47:53.765 CET [4408] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-02-19 00:47:53.765 CET [4408] LOG:  all server processes terminated; reinitializing
2021-02-19 00:47:53.809 CET [9880] LOG:  database system was interrupted; last known up at 2021-02-19 00:41:51 CET
2021-02-19 00:47:54.062 CET [9880] LOG:  database system was not properly shut down; automatic recovery in progress
2021-02-19 00:47:54.066 CET [9880] LOG:  redo starts at 0/165DA20
2021-02-19 00:47:54.066 CET [9880] LOG:  invalid record length at 0/165DB00: wanted 24, got 0
2021-02-19 00:47:54.066 CET [9880] LOG:  redo done at 0/165DAC8
2021-02-19 00:47:54.125 CET [4408] LOG:  database system is ready to accept connections
2021-02-19 00:47:54.668 CET [4408] LOG:  worker process: logical replication launcher (PID 22820) was terminated by exception 0xC000013A
2021-02-19 00:47:54.668 CET [4408] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-02-19 00:47:54.668 CET [4408] LOG:  terminating any other active server processes
2021-02-19 00:47:54.670 CET [22748] WARNING:  terminating connection because of crash of another server process
2021-02-19 00:47:54.670 CET [22748] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-02-19 00:47:54.670 CET [22748] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-02-19 00:47:54.685 CET [4408] LOG:  statistics collector process (PID 8544) was terminated by exception 0xC000013A
2021-02-19 00:47:54.685 CET [4408] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-02-19 00:47:54.686 CET [4408] LOG:  all server processes terminated; reinitializing
2021-02-19 00:47:54.729 CET [15484] LOG:  database system was interrupted; last known up at 2021-02-19 00:47:54 CET
2021-02-19 00:47:54.962 CET [15484] LOG:  database system was not properly shut down; automatic recovery in progress
2021-02-19 00:47:54.965 CET [15484] LOG:  invalid record length at 0/165DB70: wanted 24, got 0
2021-02-19 00:47:54.965 CET [15484] LOG:  redo is not required
2021-02-19 00:47:55.029 CET [4408] LOG:  database system is ready to accept connections
2021-02-19 00:47:55.500 CET [4408] LOG:  worker process: logical replication launcher (PID 20148) was terminated by exception 0xC000013A
2021-02-19 00:47:55.500 CET [4408] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-02-19 00:47:55.501 CET [4408] LOG:  terminating any other active server processes
2021-02-19 00:47:55.502 CET [7756] WARNING:  terminating connection because of crash of another server process
2021-02-19 00:47:55.502 CET [7756] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-02-19 00:47:55.502 CET [7756] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-02-19 00:47:55.518 CET [4408] LOG:  statistics collector process (PID 6332) was terminated by exception 0xC000013A
2021-02-19 00:47:55.518 CET [4408] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-02-19 00:47:55.518 CET [4408] LOG:  all server processes terminated; reinitializing
2021-02-19 00:47:55.560 CET [5400] LOG:  database system was interrupted; last known up at 2021-02-19 00:47:54 CET
2021-02-19 00:47:55.799 CET [5400] LOG:  database system was not properly shut down; automatic recovery in progress
2021-02-19 00:47:55.801 CET [5400] LOG:  invalid record length at 0/165DBE0: wanted 24, got 0
2021-02-19 00:47:55.801 CET [5400] LOG:  redo is not required
2021-02-19 00:47:55.855 CET [4408] LOG:  database system is ready to accept connections
2021-02-20 10:18:07.673 CET [11852] LOG:  listening on IPv6 address "::1", port 5432
2021-02-20 10:18:07.674 CET [11852] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-02-20 10:18:07.718 CET [16208] LOG:  database system was interrupted; last known up at 2021-02-19 00:47:55 CET
2021-02-20 10:18:07.962 CET [16208] LOG:  database system was not properly shut down; automatic recovery in progress
2021-02-20 10:18:07.965 CET [16208] LOG:  invalid record length at 0/165DC50: wanted 24, got 0
2021-02-20 10:18:07.965 CET [16208] LOG:  redo is not required
2021-02-20 10:18:08.007 CET [11852] LOG:  database system is ready to accept connections
2021-02-20 10:18:50.852 CET [14560] ERROR:  column "useid" does not exist at character 25
2021-02-20 10:18:50.852 CET [14560] HINT:  Perhaps you meant to reference the column "users.userid".
2021-02-20 10:18:50.852 CET [14560] STATEMENT:  DELETE FROM users WHERE useid=4;
2021-02-20 10:22:43.223 CET [14560] ERROR:  syntax error at or near "ON" at character 8
2021-02-20 10:22:43.223 CET [14560] STATEMENT:  UPDATE ON users(nickname) WHERE userid=0 VALUES ('hello');
2021-02-20 10:22:51.936 CET [14560] ERROR:  syntax error at or near "(" at character 13
2021-02-20 10:22:51.936 CET [14560] STATEMENT:  UPDATE users(nickname) WHERE userid=0 VALUES ('hello');
2021-02-20 10:25:36.045 CET [14560] ERROR:  syntax error at or near "hello" at character 92
2021-02-20 10:25:36.045 CET [14560] STATEMENT:  UPDATE  users SET nickname='hello', email='lol WHERE userid=0;
	UPDATE  users SET nickname='hello', email='lol' WHERE userid=0;
	SELECT * FROM users;
	=
	'
	=
	SELECT * FROM users;
2021-02-20 10:49:47.498 CET [4856] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 11:02:12.204 CET [14560] ERROR:  syntax error at or near "{" at character 46
2021-02-20 11:02:12.204 CET [14560] STATEMENT:  PREPARE updateinfo AS UPDATE users SET email={0} VALUES ($0);
2021-02-20 11:03:42.974 CET [14560] ERROR:  syntax error at or near "{" at character 46
2021-02-20 11:03:42.974 CET [14560] STATEMENT:  PREPARE updateinfo AS UPDATE users SET email={0} VALUES ($0) WHERE userid=0;
2021-02-20 11:04:25.153 CET [14560] ERROR:  syntax error at or near "{" at character 46
2021-02-20 11:04:25.153 CET [14560] STATEMENT:  PREPARE updateinfo AS UPDATE users SET email={0} WHERE userid=0;
2021-02-20 11:09:30.467 CET [14560] ERROR:  syntax error at or near ""PREPARE registration (int, text, text) AS INSERT INTO users (userid,login,password) VALUES ($1,$2,$3);"" at character 1
2021-02-20 11:09:30.467 CET [14560] STATEMENT:  "PREPARE registration (int, text, text) AS INSERT INTO users (userid,login,password) VALUES ($1,$2,$3);"
	"
	=
	"
	-
	'
	'
	END
	;
2021-02-20 11:11:02.345 CET [14560] ERROR:  syntax error at or near "{" at character 46
2021-02-20 11:11:02.345 CET [14560] STATEMENT:  PREPARE updateinfo AS UPDATE users SET email={1} WHERE userid=0 VALUES($1);
2021-02-20 11:11:21.320 CET [14560] ERROR:  syntax error at or near "{" at character 52
2021-02-20 11:11:21.320 CET [14560] STATEMENT:  PREPARE updateinfo(text) AS UPDATE users SET email={1} WHERE userid=0 VALUES($1);
2021-02-20 11:12:19.796 CET [14560] ERROR:  syntax error at or near "VALUES" at character 74
2021-02-20 11:12:19.796 CET [14560] STATEMENT:  PREPARE updateinfo(text) AS UPDATE users SET email=(text) WHERE userid=0 VALUES($1);
2021-02-20 11:25:40.322 CET [3064] ERROR:  syntax error at or near "{" at character 61
2021-02-20 11:25:40.322 CET [3064] STATEMENT:  PREPARE editUserData (text, text) AS UPDATE users SET email={1}, image={2} WHERE userid=0
2021-02-20 11:25:40.345 CET [3064] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 11:26:08.134 CET [10824] ERROR:  syntax error at or near "{" at character 61
2021-02-20 11:26:08.134 CET [10824] STATEMENT:  PREPARE editUserData (text, text) AS UPDATE users SET email={1}, image={2} WHERE userid=0
2021-02-20 11:26:08.156 CET [10824] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 11:26:43.806 CET [14560] ERROR:  prepared statement "updateinfo" already exists
2021-02-20 11:26:43.806 CET [14560] STATEMENT:  PREPARE updateinfo(text) AS UPDATE users SET email=$1 WHERE userid=0;
2021-02-20 11:26:46.939 CET [11852] LOG:  server process (PID 14560) was terminated by exception 0xC000013A
2021-02-20 11:26:46.939 CET [11852] DETAIL:  Failed process was running: PREPARE updateinfo(text) AS UPDATE users SET email=$1 WHERE userid=0;
2021-02-20 11:26:46.939 CET [11852] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-02-20 11:26:46.939 CET [11852] LOG:  terminating any other active server processes
2021-02-20 11:26:46.941 CET [21648] WARNING:  terminating connection because of crash of another server process
2021-02-20 11:26:46.941 CET [21648] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-02-20 11:26:46.941 CET [21648] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-02-20 11:26:46.952 CET [11852] LOG:  statistics collector process (PID 20836) was terminated by exception 0xC000013A
2021-02-20 11:26:46.952 CET [11852] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-02-20 11:26:46.954 CET [11852] LOG:  all server processes terminated; reinitializing
2021-02-20 11:26:46.994 CET [11552] LOG:  database system was interrupted; last known up at 2021-02-20 10:28:08 CET
2021-02-20 11:26:47.410 CET [11552] LOG:  database system was not properly shut down; automatic recovery in progress
2021-02-20 11:26:47.413 CET [11552] LOG:  redo starts at 0/165E630
2021-02-20 11:26:47.413 CET [11552] LOG:  invalid record length at 0/165E710: wanted 24, got 0
2021-02-20 11:26:47.413 CET [11552] LOG:  redo done at 0/165E6D8
2021-02-20 11:26:47.445 CET [11852] LOG:  database system is ready to accept connections
2021-02-20 11:26:51.227 CET [11852] LOG:  received fast shutdown request
2021-02-20 11:26:51.233 CET [11852] LOG:  aborting any active transactions
2021-02-20 11:26:51.237 CET [11852] LOG:  worker process: logical replication launcher (PID 9512) exited with exit code 1
2021-02-20 11:26:51.245 CET [5096] LOG:  shutting down
2021-02-20 11:26:51.287 CET [11852] LOG:  database system is shut down
2021-02-20 11:26:55.677 CET [12768] LOG:  listening on IPv6 address "::1", port 5432
2021-02-20 11:26:55.677 CET [12768] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-02-20 11:26:55.724 CET [4380] LOG:  database system was shut down at 2021-02-20 11:26:51 CET
2021-02-20 11:26:55.747 CET [12768] LOG:  database system is ready to accept connections
2021-02-20 11:28:06.599 CET [13012] ERROR:  column "image" of relation "users" does not exist at character 65
2021-02-20 11:28:06.599 CET [13012] STATEMENT:  PREPARE editUserData (text, text) AS UPDATE users SET email=$1, image=$2 WHERE userid=0
2021-02-20 11:28:06.624 CET [13012] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 11:30:10.653 CET [14948] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 12:16:47.067 CET [2500] ERROR:  relation "stats" does not exist at character 15
2021-02-20 12:16:47.067 CET [2500] STATEMENT:  SELECT * FROM stats;
2021-02-20 12:33:15.859 CET [2500] ERROR:  syntax error at or near "user" at character 13
2021-02-20 12:33:15.859 CET [2500] STATEMENT:  DELETE from user;
2021-02-20 12:50:12.498 CET [6780] ERROR:  syntax error at or near "BY" at character 31
2021-02-20 12:50:12.498 CET [6780] STATEMENT:  SELECT * FROM scoreboard ODER BY wins ASC
2021-02-20 12:50:14.005 CET [6780] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 12:50:40.609 CET [1592] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 12:53:09.897 CET [19108] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 12:55:56.059 CET [2500] ERROR:  relation "multimediacontent" does not exist at character 13
2021-02-20 12:55:56.059 CET [2500] STATEMENT:  SELECT FROM multimediacontent
	;
2021-02-20 12:56:43.052 CET [2500] ERROR:  syntax error at or near ";" at character 215
2021-02-20 12:56:43.052 CET [2500] STATEMENT:  CREATE TABLE multimedia_content(
	mcid int primary key,
	title varchar(32),
	artist varchar(32),
	album varchar(32),
	rating float,
	genre varchar(32),
	lenght int,
	filetype varchar(8),
	filesize int,
	filepath varchar(64)
	;
	)
	;
2021-02-20 12:57:47.657 CET [2500] ERROR:  cannot drop table multimedia_content because other objects depend on it
2021-02-20 12:57:47.657 CET [2500] DETAIL:  constraint library_mcid_fkey on table library depends on table multimedia_content
	constraint playlist_mcid_fkey on table playlist depends on table multimedia_content
	constraint playlist_history_mcid_fkey on table playlist_history depends on table multimedia_content
2021-02-20 12:57:47.657 CET [2500] HINT:  Use DROP ... CASCADE to drop the dependent objects too.
2021-02-20 12:57:47.657 CET [2500] STATEMENT:  DROP TABLE multimedia_content
	;
2021-02-20 12:59:46.097 CET [2500] ERROR:  syntax error at or near "0" at character 33
2021-02-20 12:59:46.097 CET [2500] STATEMENT:  INSERT INTO multimedia_content (0, 'Test_Song', 'testartist', 'testalbum', 3.5, 'rock', 45, )
	;
2021-02-20 13:00:22.091 CET [2500] ERROR:  syntax error at or near "0" at character 33
2021-02-20 13:00:22.091 CET [2500] STATEMENT:  INSERT INTO multimedia_content (0, 'Test_Song', 'testartist', 'testalbum', 3.5, 'rock', 45, 'yt', 0, 'http://youtube.com');
2021-02-20 13:18:20.876 CET [4460] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 13:18:30.156 CET [12148] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 13:19:00.934 CET [15868] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 13:19:20.659 CET [21152] ERROR:  column "testsong" does not exist at character 19
2021-02-20 13:19:20.659 CET [21152] STATEMENT:  EXECUTE addMmc (1,testSong,songo)
2021-02-20 13:20:50.551 CET [17612] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 13:43:23.638 CET [23056] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 13:44:10.894 CET [11528] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 13:47:44.710 CET [8660] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 14:02:37.074 CET [4972] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 14:02:57.255 CET [7212] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 14:04:00.507 CET [2640] ERROR:  insert or update on table "playlist" violates foreign key constraint "playlist_mcid_fkey"
2021-02-20 14:04:00.507 CET [2640] DETAIL:  Key (mcid)=(5) is not present in table "multimedia_content".
2021-02-20 14:04:00.507 CET [2640] STATEMENT:  INSERT INTO playlist VALUES (5,4)
2021-02-20 14:04:01.908 CET [2640] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 14:05:02.544 CET [11916] ERROR:  insert or update on table "playlist" violates foreign key constraint "playlist_mcid_fkey"
2021-02-20 14:05:02.544 CET [11916] DETAIL:  Key (mcid)=(5) is not present in table "multimedia_content".
2021-02-20 14:05:02.544 CET [11916] STATEMENT:  INSERT INTO playlist VALUES (5,4)
2021-02-20 14:18:05.116 CET [21676] ERROR:  syntax error at or near "FROM" at character 19
2021-02-20 14:18:05.116 CET [21676] STATEMENT:  UPDATE song_order FROM playlist SET song_order=2 WHERE song_order=-1
2021-02-20 14:18:06.483 CET [21676] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 14:32:33.259 CET [2496] ERROR:  column "songorder" does not exist at character 36
2021-02-20 14:32:33.259 CET [2496] HINT:  Perhaps you meant to reference the column "playlist.song_order".
2021-02-20 14:32:33.259 CET [2496] STATEMENT:  SELECT mcid FROM playlist ORDER BY songorder ASC
2021-02-20 14:32:34.936 CET [2496] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 14:32:42.513 CET [23464] ERROR:  column "songorder" does not exist at character 36
2021-02-20 14:32:42.513 CET [23464] HINT:  Perhaps you meant to reference the column "playlist.song_order".
2021-02-20 14:32:42.513 CET [23464] STATEMENT:  SELECT mcid FROM playlist ORDER BY songorder ASC
2021-02-20 14:32:43.957 CET [23464] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 14:32:56.841 CET [21124] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 14:56:02.648 CET [6268] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 15:01:07.588 CET [9092] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 15:02:09.212 CET [21332] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 15:02:29.910 CET [17192] ERROR:  invalid input syntax for type double precision: "3,4" at character 72
2021-02-20 15:02:29.910 CET [17192] STATEMENT:  EXECUTE addMmc (7,'Yoo','https://www.youtube.com/watch?v=inMCT9fXjg4', '3,4')
2021-02-20 15:04:56.238 CET [2500] ERROR:  column "rating" is of type double precision but expression is of type text at character 54
2021-02-20 15:04:56.238 CET [2500] HINT:  You will need to rewrite or cast the expression.
2021-02-20 15:04:56.238 CET [2500] STATEMENT:  INSERT into multimedia_content(mcid,rating) VALUES(6,replace('3,4',',','.'));
2021-02-20 15:05:24.771 CET [2500] ERROR:  duplicate key value violates unique constraint "multimedia_content_pkey"
2021-02-20 15:05:24.771 CET [2500] DETAIL:  Key (mcid)=(6) already exists.
2021-02-20 15:05:24.771 CET [2500] STATEMENT:  INSERT into multimedia_content(mcid,rating) VALUES(6,replace('3,4',',','.')::float);
2021-02-20 17:36:10.747 CET [14256] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 17:36:42.856 CET [17656] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 17:38:49.855 CET [22124] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 17:39:00.104 CET [21208] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 17:40:14.028 CET [23216] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 17:55:42.002 CET [2500] ERROR:  update or delete on table "multimedia_content" violates foreign key constraint "playlist_mcid_fkey" on table "playlist"
2021-02-20 17:55:42.002 CET [2500] DETAIL:  Key (mcid)=(2) is still referenced from table "playlist".
2021-02-20 17:55:42.002 CET [2500] STATEMENT:  DELETE FROM multimedia_content;
2021-02-20 17:56:42.664 CET [16576] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:04:58.834 CET [15856] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:21:58.157 CET [15308] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:22:33.793 CET [13072] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:22:37.539 CET [18864] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:23:45.178 CET [13116] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:24:05.714 CET [21740] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:33:16.106 CET [21932] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-20 18:33:16.106 CET [21932] DETAIL:  Key (userid)=(0) already exists.
2021-02-20 18:33:16.106 CET [21932] STATEMENT:  EXECUTE registration (0,'?KH???d%?!s??????s? v??;S?t???','Hox???=?j???G????;?#??.,[?')
2021-02-20 18:33:39.829 CET [8732] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-20 18:33:39.829 CET [8732] DETAIL:  Key (userid)=(0) already exists.
2021-02-20 18:33:39.829 CET [8732] STATEMENT:  EXECUTE registration (0,'?KH???d%?!s??????s? v??;S?t???','Hox???=?j???G????;?#??.,[?')
2021-02-20 18:35:45.816 CET [19908] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-20 18:35:45.816 CET [19908] DETAIL:  Key (userid)=(0) already exists.
2021-02-20 18:35:45.816 CET [19908] STATEMENT:  EXECUTE registration (0,'?KH???d%?!s??????s? v??;S?t???','Hox???=?j???G????;?#??.,[?')
2021-02-20 18:42:20.272 CET [16668] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-20 18:42:20.272 CET [16668] DETAIL:  Key (userid)=(0) already exists.
2021-02-20 18:42:20.272 CET [16668] STATEMENT:  EXECUTE registration (0,'?KH???d%?!s??????s? v??;S?t???','Hox???=?j???G????;?#??.,[?')
2021-02-20 18:42:20.284 CET [16668] ERROR:  column "name" does not exist at character 56
2021-02-20 18:42:20.284 CET [16668] STATEMENT:  PREPARE findUsername AS SELECT userid FROM users WHERE name=$1
2021-02-20 18:42:22.741 CET [16668] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:42:35.809 CET [7172] ERROR:  column "name" does not exist at character 56
2021-02-20 18:42:35.809 CET [7172] STATEMENT:  PREPARE findUsername AS SELECT userid FROM users WHERE name=$1
2021-02-20 18:42:38.617 CET [7172] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:43:22.571 CET [18404] ERROR:  column "username" does not exist at character 56
2021-02-20 18:43:22.571 CET [18404] STATEMENT:  PREPARE findUsername AS SELECT userid FROM users WHERE username=$1
2021-02-20 18:43:25.388 CET [18404] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:46:00.586 CET [24076] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:46:36.346 CET [2500] ERROR:  update or delete on table "users" violates foreign key constraint "scoreboard_userid_fkey" on table "scoreboard"
2021-02-20 18:46:36.346 CET [2500] DETAIL:  Key (userid)=(1) is still referenced from table "scoreboard".
2021-02-20 18:46:36.346 CET [2500] STATEMENT:  DELETE FROM users;
2021-02-20 18:47:26.386 CET [18972] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:47:38.566 CET [21208] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-20 18:47:38.566 CET [21208] DETAIL:  Key (login)=(?KH???d%?!s??????s? v??;S?t???) already exists.
2021-02-20 18:47:38.566 CET [21208] STATEMENT:  EXECUTE registration (1,'?KH???d%?!s??????s? v??;S?t???','Hox???=?j???G????;?#??.,[?')
2021-02-20 18:55:00.211 CET [20040] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:56:17.068 CET [7484] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 18:56:46.197 CET [2500] ERROR:  relation "stats" does not exist at character 15
2021-02-20 18:56:46.197 CET [2500] STATEMENT:  SELECT * FROM stats;
2021-02-20 18:56:50.348 CET [2500] ERROR:  relation "statistic" does not exist at character 15
2021-02-20 18:56:50.348 CET [2500] STATEMENT:  SELECT * FROM statistic;
2021-02-20 19:11:35.354 CET [11884] ERROR:  could not determine data type of parameter $1
2021-02-20 19:11:35.354 CET [11884] STATEMENT:  SELECT name FROM multimedia_content WHERE mcid=$3
2021-02-20 19:11:59.157 CET [24000] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 19:11:59.158 CET [11884] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 19:13:16.955 CET [15844] ERROR:  could not determine data type of parameter $1
2021-02-20 19:13:16.955 CET [15844] STATEMENT:  SELECT name FROM multimedia_content WHERE mcid=$3
2021-02-20 19:13:26.311 CET [5616] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-20 19:13:26.311 CET [15844] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:11:12.801 CET [15144] ERROR:  insufficient data left in message
2021-02-21 12:13:25.152 CET [1332] ERROR:  insufficient data left in message
2021-02-21 12:14:46.954 CET [2500] ERROR:  syntax error at or near "" at character 54
2021-02-21 12:14:46.954 CET [2500] STATEMENT:  EXECUTE registration (1,'???`?_??l?r?c??Hzc?'?????9 ;
	;
	;
	=
	)
	;
2021-02-21 12:40:49.494 CET [19996] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:40:49.494 CET [19996] DETAIL:  Key (login)=(C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4) already exists.
2021-02-21 12:40:49.494 CET [19996] STATEMENT:  EXECUTE registration (3,'C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 12:41:33.850 CET [19996] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:41:46.624 CET [25264] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:41:46.624 CET [25264] DETAIL:  Key (login)=(3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB) already exists.
2021-02-21 12:41:46.624 CET [25264] STATEMENT:  EXECUTE registration (3,'3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 12:44:08.646 CET [25264] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:44:15.984 CET [4928] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:44:15.984 CET [4928] DETAIL:  Key (login)=(3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB) already exists.
2021-02-21 12:44:15.984 CET [4928] STATEMENT:  EXECUTE registration (3,'3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 12:48:21.070 CET [4928] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:48:28.784 CET [11524] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:48:28.784 CET [11524] DETAIL:  Key (login)=(3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB) already exists.
2021-02-21 12:48:28.784 CET [11524] STATEMENT:  EXECUTE registration (3,'3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 12:48:30.313 CET [11524] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:50:17.034 CET [6428] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:50:17.034 CET [6428] DETAIL:  Key (login)=(3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB) already exists.
2021-02-21 12:50:17.034 CET [6428] STATEMENT:  EXECUTE registration (3,'3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 12:50:39.579 CET [6428] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:50:48.098 CET [13088] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:50:48.098 CET [13088] DETAIL:  Key (login)=(C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4) already exists.
2021-02-21 12:50:48.098 CET [13088] STATEMENT:  EXECUTE registration (3,'C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 12:50:48.347 CET [13088] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:50:48.347 CET [13088] DETAIL:  Key (login)=(3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB) already exists.
2021-02-21 12:50:48.347 CET [13088] STATEMENT:  EXECUTE registration (3,'3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-21 12:50:48.818 CET [13088] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:50:48.818 CET [13088] DETAIL:  Key (login)=(C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4) already exists.
2021-02-21 12:50:48.818 CET [13088] STATEMENT:  EXECUTE registration (4,'C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 12:50:49.061 CET [13088] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:50:49.061 CET [13088] DETAIL:  Key (login)=(C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4) already exists.
2021-02-21 12:50:49.061 CET [13088] STATEMENT:  EXECUTE registration (4,'C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 12:50:52.334 CET [21916] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:50:52.335 CET [13088] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:50:52.335 CET [4620] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:50:52.335 CET [4128] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:51:34.424 CET [2496] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:51:34.424 CET [2496] DETAIL:  Key (login)=(C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4) already exists.
2021-02-21 12:51:34.424 CET [2496] STATEMENT:  EXECUTE registration (4,'C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 12:51:34.663 CET [2496] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:51:34.663 CET [2496] DETAIL:  Key (login)=(3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB) already exists.
2021-02-21 12:51:34.663 CET [2496] STATEMENT:  EXECUTE registration (4,'3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-21 12:51:34.894 CET [2496] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:51:34.894 CET [2496] DETAIL:  Key (login)=(8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918) already exists.
2021-02-21 12:51:34.894 CET [2496] STATEMENT:  EXECUTE registration (4,'8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-21 12:51:35.120 CET [2496] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:51:35.120 CET [2496] DETAIL:  Key (login)=(C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4) already exists.
2021-02-21 12:51:35.120 CET [2496] STATEMENT:  EXECUTE registration (4,'C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 12:51:35.361 CET [2496] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:51:35.361 CET [2496] DETAIL:  Key (login)=(C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4) already exists.
2021-02-21 12:51:35.361 CET [2496] STATEMENT:  EXECUTE registration (4,'C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 12:51:38.644 CET [2496] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:51:38.644 CET [24428] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:51:38.645 CET [18156] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:51:38.645 CET [24944] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:58:01.527 CET [25316] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:58:01.527 CET [25316] DETAIL:  Key (login)=(C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4) already exists.
2021-02-21 12:58:01.527 CET [25316] STATEMENT:  EXECUTE registration (4,'C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 12:58:01.762 CET [25316] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:58:01.762 CET [25316] DETAIL:  Key (login)=(3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB) already exists.
2021-02-21 12:58:01.762 CET [25316] STATEMENT:  EXECUTE registration (4,'3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-21 12:58:02.003 CET [25316] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:58:02.003 CET [25316] DETAIL:  Key (login)=(8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918) already exists.
2021-02-21 12:58:02.003 CET [25316] STATEMENT:  EXECUTE registration (4,'8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-21 12:58:02.221 CET [25316] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:58:02.221 CET [25316] DETAIL:  Key (login)=(C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4) already exists.
2021-02-21 12:58:02.221 CET [25316] STATEMENT:  EXECUTE registration (4,'C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 12:58:02.448 CET [25316] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 12:58:02.448 CET [25316] DETAIL:  Key (login)=(C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4) already exists.
2021-02-21 12:58:02.448 CET [25316] STATEMENT:  EXECUTE registration (4,'C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 12:58:05.701 CET [25316] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:58:05.701 CET [14808] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:58:05.701 CET [16116] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 12:58:05.701 CET [16436] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:04:37.091 CET [4928] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:04:37.091 CET [4928] DETAIL:  Key (login)=(C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4) already exists.
2021-02-21 13:04:37.091 CET [4928] STATEMENT:  EXECUTE registration (4,'C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 13:04:37.327 CET [4928] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:04:37.327 CET [4928] DETAIL:  Key (login)=(3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB) already exists.
2021-02-21 13:04:37.327 CET [4928] STATEMENT:  EXECUTE registration (4,'3FF9FB1BB2608D5FF3F66C841072F0638982487A63DD27D5B2DEB3C939001ABB','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-21 13:04:37.562 CET [4928] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:04:37.562 CET [4928] DETAIL:  Key (login)=(8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918) already exists.
2021-02-21 13:04:37.562 CET [4928] STATEMENT:  EXECUTE registration (4,'8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-21 13:04:37.789 CET [4928] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:04:37.789 CET [4928] DETAIL:  Key (login)=(C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4) already exists.
2021-02-21 13:04:37.789 CET [4928] STATEMENT:  EXECUTE registration (4,'C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 13:04:38.022 CET [4928] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:04:38.022 CET [4928] DETAIL:  Key (login)=(C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4) already exists.
2021-02-21 13:04:38.022 CET [4928] STATEMENT:  EXECUTE registration (4,'C84B489886BC6425E6217396AE9DBFDCD47302B9207F76C1AA3B53CF743FE1D4','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 13:05:27.637 CET [4928] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:05:27.637 CET [15188] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:05:27.637 CET [18728] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:05:27.637 CET [8568] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:47:22.417 CET [2212] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:47:22.417 CET [2212] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 13:47:22.417 CET [2212] STATEMENT:  EXECUTE registration (7,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 13:47:22.658 CET [2212] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:47:22.658 CET [2212] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 13:47:22.658 CET [2212] STATEMENT:  EXECUTE registration (7,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 13:49:40.880 CET [2500] ERROR:  syntax error at or near "," at character 23
2021-02-21 13:49:40.880 CET [2500] STATEMENT:  DELETE FROM scoreboard, library,users;
2021-02-21 13:52:19.233 CET [2212] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:52:19.233 CET [10200] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:52:19.233 CET [25392] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:52:19.233 CET [9684] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:52:28.098 CET [16716] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:52:28.098 CET [16716] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 13:52:28.098 CET [16716] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 13:52:28.329 CET [16716] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:52:28.329 CET [16716] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 13:52:28.329 CET [16716] STATEMENT:  EXECUTE registration (3,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 13:55:27.044 CET [4620] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:55:27.045 CET [16716] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:55:27.045 CET [7144] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:55:27.045 CET [20820] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:57:47.343 CET [5948] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:57:47.343 CET [5948] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 13:57:47.343 CET [5948] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 13:57:47.588 CET [5948] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:57:47.588 CET [5948] DETAIL:  Key (login)=(altenhof) already exists.
2021-02-21 13:57:47.588 CET [5948] STATEMENT:  EXECUTE registration (3,'altenhof','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-21 13:57:47.814 CET [5948] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:57:47.814 CET [5948] DETAIL:  Key (login)=(admin) already exists.
2021-02-21 13:57:47.814 CET [5948] STATEMENT:  EXECUTE registration (3,'admin','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-21 13:57:48.039 CET [5948] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:57:48.039 CET [5948] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 13:57:48.039 CET [5948] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 13:57:48.283 CET [5948] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 13:57:48.283 CET [5948] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 13:57:48.283 CET [5948] STATEMENT:  EXECUTE registration (3,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 13:59:48.714 CET [5948] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:59:48.714 CET [9544] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:59:48.714 CET [24584] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 13:59:48.714 CET [12516] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:07:34.537 CET [13012] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:07:34.537 CET [7512] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:07:34.538 CET [3944] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:07:34.538 CET [14600] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:07:45.390 CET [17232] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:07:45.390 CET [15144] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:07:45.390 CET [23916] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:07.332 CET [11628] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:07.332 CET [22872] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:07.333 CET [15100] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:07.333 CET [10312] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:15.413 CET [9396] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 14:14:15.413 CET [9396] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 14:14:15.413 CET [9396] STATEMENT:  EXECUTE registration (0,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 14:14:15.646 CET [9396] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 14:14:15.646 CET [9396] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 14:14:15.646 CET [9396] STATEMENT:  EXECUTE registration (0,'altenhof','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-21 14:14:15.878 CET [9396] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 14:14:15.878 CET [9396] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 14:14:15.878 CET [9396] STATEMENT:  EXECUTE registration (0,'admin','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-21 14:14:16.106 CET [9396] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 14:14:16.106 CET [9396] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 14:14:16.106 CET [9396] STATEMENT:  EXECUTE registration (0,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 14:14:16.349 CET [9396] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 14:14:16.349 CET [9396] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 14:14:16.349 CET [9396] STATEMENT:  EXECUTE registration (0,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 14:14:21.867 CET [9396] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:21.868 CET [24868] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:21.868 CET [12456] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:21.868 CET [21188] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:21.868 CET [18916] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:21.868 CET [1184] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:21.868 CET [10032] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:21.868 CET [22360] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:21.868 CET [18660] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:21.868 CET [11928] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:14:21.868 CET [11656] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:23:08.044 CET [22852] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 14:23:08.044 CET [22852] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 14:23:08.044 CET [22852] STATEMENT:  EXECUTE registration (0,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 14:23:08.283 CET [22852] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 14:23:08.283 CET [22852] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 14:23:08.283 CET [22852] STATEMENT:  EXECUTE registration (0,'altenhof','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-21 14:23:08.506 CET [22852] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 14:23:08.506 CET [22852] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 14:23:08.506 CET [22852] STATEMENT:  EXECUTE registration (0,'admin','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-21 14:23:08.754 CET [22852] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 14:23:08.754 CET [22852] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 14:23:08.754 CET [22852] STATEMENT:  EXECUTE registration (0,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 14:23:08.985 CET [22852] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 14:23:08.985 CET [22852] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 14:23:08.985 CET [22852] STATEMENT:  EXECUTE registration (0,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 14:23:13.589 CET [20920] ERROR:  column "username" does not exist at character 8
2021-02-21 14:23:13.589 CET [20920] STATEMENT:  SELECT username FROM users WHERE userid=0
2021-02-21 14:23:15.060 CET [13236] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:23:15.060 CET [22852] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:23:15.061 CET [5928] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:23:15.061 CET [18848] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:23:15.061 CET [13424] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:23:15.062 CET [13960] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:23:15.062 CET [21668] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:23:15.062 CET [20920] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:23:15.062 CET [23540] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:23:15.062 CET [16352] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:24:15.144 CET [6508] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:24:15.144 CET [6508] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 14:24:15.144 CET [6508] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 14:24:15.382 CET [6508] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:24:15.382 CET [6508] DETAIL:  Key (login)=(altenhof) already exists.
2021-02-21 14:24:15.382 CET [6508] STATEMENT:  EXECUTE registration (3,'altenhof','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-21 14:24:15.616 CET [6508] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:24:15.616 CET [6508] DETAIL:  Key (login)=(admin) already exists.
2021-02-21 14:24:15.616 CET [6508] STATEMENT:  EXECUTE registration (3,'admin','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-21 14:24:15.853 CET [6508] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:24:15.853 CET [6508] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 14:24:15.853 CET [6508] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 14:24:16.084 CET [6508] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:24:16.084 CET [6508] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 14:24:16.084 CET [6508] STATEMENT:  EXECUTE registration (3,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 14:24:22.187 CET [6508] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:24:22.187 CET [15436] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:24:22.188 CET [17700] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:24:22.188 CET [7880] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:24:22.188 CET [17344] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:24:22.188 CET [12352] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:24:22.188 CET [21436] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:24:22.188 CET [15608] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:24:22.188 CET [9092] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:24:22.188 CET [21604] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:26:01.080 CET [20088] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:26:01.080 CET [20088] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 14:26:01.080 CET [20088] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 14:26:01.310 CET [20088] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:26:01.310 CET [20088] DETAIL:  Key (login)=(altenhof) already exists.
2021-02-21 14:26:01.310 CET [20088] STATEMENT:  EXECUTE registration (3,'altenhof','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-21 14:26:01.549 CET [20088] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:26:01.549 CET [20088] DETAIL:  Key (login)=(admin) already exists.
2021-02-21 14:26:01.549 CET [20088] STATEMENT:  EXECUTE registration (3,'admin','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-21 14:26:01.772 CET [20088] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:26:01.772 CET [20088] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 14:26:01.772 CET [20088] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 14:26:02.017 CET [20088] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:26:02.017 CET [20088] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 14:26:02.017 CET [20088] STATEMENT:  EXECUTE registration (3,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 14:26:07.887 CET [4120] ERROR:  column "album" specified more than once at character 101
2021-02-21 14:26:07.887 CET [4120] STATEMENT:  PREPARE addMmc AS INSERT INTO multimedia_content(mcid, name, filepath, rating, genre, title, album, album) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
2021-02-21 14:26:10.831 CET [23868] ERROR:  insert or update on table "playlist" violates foreign key constraint "playlist_mcid_fkey"
2021-02-21 14:26:10.831 CET [23868] DETAIL:  Key (mcid)=(-1) is not present in table "multimedia_content".
2021-02-21 14:26:10.831 CET [23868] STATEMENT:  INSERT INTO playlist VALUES (-1,4)
2021-02-21 14:26:11.058 CET [23868] ERROR:  insert or update on table "playlist" violates foreign key constraint "playlist_mcid_fkey"
2021-02-21 14:26:11.058 CET [23868] DETAIL:  Key (mcid)=(-1) is not present in table "multimedia_content".
2021-02-21 14:26:11.058 CET [23868] STATEMENT:  INSERT INTO playlist VALUES (-1,4)
2021-02-21 14:26:11.534 CET [23868] ERROR:  insert or update on table "playlist" violates foreign key constraint "playlist_mcid_fkey"
2021-02-21 14:26:11.534 CET [23868] DETAIL:  Key (mcid)=(-1) is not present in table "multimedia_content".
2021-02-21 14:26:11.534 CET [23868] STATEMENT:  INSERT INTO playlist VALUES (-1,5)
2021-02-21 14:30:05.440 CET [8472] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.440 CET [8128] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.440 CET [19260] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.440 CET [20088] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.441 CET [22284] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.442 CET [5932] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.442 CET [5244] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.442 CET [18716] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.443 CET [22020] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.443 CET [21332] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.443 CET [4120] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.443 CET [22164] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.443 CET [19184] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.443 CET [21324] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.443 CET [23868] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.443 CET [5620] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.443 CET [24412] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:05.443 CET [8456] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:51.467 CET [12544] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:51.468 CET [4472] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:51.468 CET [19236] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:30:51.468 CET [23116] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:31:44.507 CET [19548] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:31:44.507 CET [19548] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 14:31:44.507 CET [19548] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 14:31:44.745 CET [19548] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:31:44.745 CET [19548] DETAIL:  Key (login)=(altenhof) already exists.
2021-02-21 14:31:44.745 CET [19548] STATEMENT:  EXECUTE registration (3,'altenhof','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-21 14:31:44.986 CET [19548] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:31:44.986 CET [19548] DETAIL:  Key (login)=(admin) already exists.
2021-02-21 14:31:44.986 CET [19548] STATEMENT:  EXECUTE registration (3,'admin','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-21 14:31:45.216 CET [19548] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:31:45.216 CET [19548] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 14:31:45.216 CET [19548] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 14:31:45.455 CET [19548] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:31:45.455 CET [19548] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 14:31:45.455 CET [19548] STATEMENT:  EXECUTE registration (3,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 14:32:10.133 CET [14588] ERROR:  column "album" specified more than once at character 101
2021-02-21 14:32:10.133 CET [14588] STATEMENT:  PREPARE addMmc AS INSERT INTO multimedia_content(mcid, name, filepath, rating, genre, title, album, album) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
2021-02-21 14:32:13.097 CET [20416] ERROR:  insert or update on table "playlist" violates foreign key constraint "playlist_mcid_fkey"
2021-02-21 14:32:13.097 CET [20416] DETAIL:  Key (mcid)=(-1) is not present in table "multimedia_content".
2021-02-21 14:32:13.097 CET [20416] STATEMENT:  INSERT INTO playlist VALUES (-1,7)
2021-02-21 14:32:13.324 CET [20416] ERROR:  insert or update on table "playlist" violates foreign key constraint "playlist_mcid_fkey"
2021-02-21 14:32:13.324 CET [20416] DETAIL:  Key (mcid)=(-1) is not present in table "multimedia_content".
2021-02-21 14:32:13.324 CET [20416] STATEMENT:  INSERT INTO playlist VALUES (-1,7)
2021-02-21 14:32:13.802 CET [20416] ERROR:  insert or update on table "playlist" violates foreign key constraint "playlist_mcid_fkey"
2021-02-21 14:32:13.802 CET [20416] DETAIL:  Key (mcid)=(-1) is not present in table "multimedia_content".
2021-02-21 14:32:13.802 CET [20416] STATEMENT:  INSERT INTO playlist VALUES (-1,8)
2021-02-21 14:34:36.176 CET [2500] ERROR:  relation "lib" does not exist at character 15
2021-02-21 14:34:36.176 CET [2500] STATEMENT:  select * from lib
	;
2021-02-21 14:37:16.347 CET [18700] ERROR:  column "album" specified more than once at character 101
2021-02-21 14:37:16.347 CET [18700] STATEMENT:  PREPARE addMmc AS INSERT INTO multimedia_content(mcid, name, filepath, rating, genre, title, album, album) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
2021-02-21 14:41:27.342 CET [19548] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.344 CET [19636] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.344 CET [18144] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.344 CET [20820] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.344 CET [9680] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.345 CET [19736] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.345 CET [21436] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.345 CET [17864] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.345 CET [14588] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.345 CET [7812] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.345 CET [6588] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.346 CET [18700] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.346 CET [10756] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.346 CET [17324] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.346 CET [10664] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.346 CET [8036] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.346 CET [20416] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.347 CET [13160] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.347 CET [24228] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.347 CET [18916] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:27.348 CET [23600] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:41:40.298 CET [1300] ERROR:  value too long for type character varying(8)
2021-02-21 14:41:40.298 CET [1300] STATEMENT:  EXECUTE addMmc (2,'Good_Mood_Song','https://youtu.be/H9cmPE88a_0', replace('4',',','.')::float, 'Pop', 'Duck Tales Intro', 'Theme Songs', 'Theme Songs')
2021-02-21 14:42:47.907 CET [1300] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:42:47.907 CET [16800] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:42:54.004 CET [24600] ERROR:  value too long for type character varying(8)
2021-02-21 14:42:54.004 CET [24600] STATEMENT:  EXECUTE addMmc (2,'Good_Mood_Song','https://youtu.be/H9cmPE88a_0', replace('4',',','.')::float, 'Pop', 'Duck Tales Intro', 'Theme Songs', 'Theme Songs')
2021-02-21 14:44:25.482 CET [16064] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:44:25.482 CET [24600] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:49:05.795 CET [24144] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:49:05.795 CET [12076] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:49:31.534 CET [13604] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:49:31.534 CET [13604] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 14:49:31.534 CET [13604] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 14:49:31.773 CET [13604] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 14:49:31.773 CET [13604] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 14:49:31.773 CET [13604] STATEMENT:  EXECUTE registration (3,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 14:49:41.396 CET [22728] ERROR:  insert or update on table "playlist" violates foreign key constraint "playlist_mcid_fkey"
2021-02-21 14:49:41.396 CET [22728] DETAIL:  Key (mcid)=(-1) is not present in table "multimedia_content".
2021-02-21 14:49:41.396 CET [22728] STATEMENT:  INSERT INTO playlist VALUES (-1,7)
2021-02-21 14:52:22.339 CET [2500] ERROR:  update or delete on table "multimedia_content" violates foreign key constraint "library_mcid_fkey" on table "library"
2021-02-21 14:52:22.339 CET [2500] DETAIL:  Key (mcid)=(0) is still referenced from table "library".
2021-02-21 14:52:22.339 CET [2500] STATEMENT:  DELETE FROM multimedia_content;
2021-02-21 14:56:54.039 CET [13604] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.039 CET [22104] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.040 CET [10892] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.040 CET [10680] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.041 CET [19512] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.041 CET [7868] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.041 CET [20236] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.041 CET [21720] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.041 CET [4996] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.041 CET [11756] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.041 CET [16248] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.042 CET [15972] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.042 CET [6564] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.042 CET [22728] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.042 CET [18320] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.042 CET [21124] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.042 CET [4356] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:56:54.042 CET [8092] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:59:44.866 CET [8888] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 14:59:58.241 CET [24100] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:25.873 CET [16076] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 17:33:25.873 CET [16076] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 17:33:25.873 CET [16076] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 17:33:26.127 CET [16076] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 17:33:26.127 CET [16076] DETAIL:  Key (login)=(altenhof) already exists.
2021-02-21 17:33:26.127 CET [16076] STATEMENT:  EXECUTE registration (3,'altenhof','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-21 17:33:26.350 CET [16076] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 17:33:26.350 CET [16076] DETAIL:  Key (login)=(admin) already exists.
2021-02-21 17:33:26.350 CET [16076] STATEMENT:  EXECUTE registration (3,'admin','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-21 17:33:26.582 CET [16076] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 17:33:26.582 CET [16076] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 17:33:26.582 CET [16076] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 17:33:26.815 CET [16076] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 17:33:26.815 CET [16076] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 17:33:26.815 CET [16076] STATEMENT:  EXECUTE registration (3,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 17:33:38.603 CET [16076] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.604 CET [18844] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.605 CET [23780] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.605 CET [5904] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.605 CET [12100] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.606 CET [18260] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.606 CET [10568] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.606 CET [14864] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.606 CET [20832] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.606 CET [23516] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.606 CET [9396] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.606 CET [16476] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.606 CET [24256] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.606 CET [17224] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.606 CET [14532] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.607 CET [14020] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.607 CET [18680] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:33:38.606 CET [10512] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:40:39.627 CET [4552] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:42:57.362 CET [10044] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:43:25.658 CET [12120] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:48:09.160 CET [24752] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 17:48:34.424 CET [18048] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 18:29:08.675 CET [21248] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 18:29:08.676 CET [3080] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 18:29:35.871 CET [20552] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 18:33:16.198 CET [6360] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 18:39:01.269 CET [16532] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:12:45.629 CET [23124] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:13:32.615 CET [17728] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:13:45.775 CET [17520] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 20:13:45.775 CET [17520] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 20:13:45.775 CET [17520] STATEMENT:  EXECUTE registration (0,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 20:13:46.006 CET [17520] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 20:13:46.006 CET [17520] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 20:13:46.006 CET [17520] STATEMENT:  EXECUTE registration (0,'altenhof','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-21 20:13:46.236 CET [17520] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 20:13:46.236 CET [17520] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 20:13:46.236 CET [17520] STATEMENT:  EXECUTE registration (0,'admin','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-21 20:13:46.468 CET [17520] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 20:13:46.468 CET [17520] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 20:13:46.468 CET [17520] STATEMENT:  EXECUTE registration (0,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 20:13:46.687 CET [17520] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-21 20:13:46.687 CET [17520] DETAIL:  Key (userid)=(0) already exists.
2021-02-21 20:13:46.687 CET [17520] STATEMENT:  EXECUTE registration (0,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 20:15:28.218 CET [10360] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.219 CET [17520] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.220 CET [5004] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.220 CET [18468] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.220 CET [16968] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.220 CET [21060] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.221 CET [25396] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.221 CET [21440] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.221 CET [24372] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.221 CET [16772] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.221 CET [13700] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.221 CET [22832] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.221 CET [18744] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.221 CET [13220] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.221 CET [3128] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.221 CET [8120] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.222 CET [8252] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.222 CET [15500] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.222 CET [9420] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:15:28.222 CET [2696] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:16:40.295 CET [20472] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 20:16:40.295 CET [20472] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 20:16:40.295 CET [20472] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 20:16:40.520 CET [20472] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 20:16:40.520 CET [20472] DETAIL:  Key (login)=(altenhof) already exists.
2021-02-21 20:16:40.520 CET [20472] STATEMENT:  EXECUTE registration (3,'altenhof','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-21 20:16:40.750 CET [20472] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 20:16:40.750 CET [20472] DETAIL:  Key (login)=(admin) already exists.
2021-02-21 20:16:40.750 CET [20472] STATEMENT:  EXECUTE registration (3,'admin','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-21 20:16:40.971 CET [20472] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 20:16:40.971 CET [20472] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 20:16:40.971 CET [20472] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 20:16:41.212 CET [20472] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 20:16:41.212 CET [20472] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 20:16:41.212 CET [20472] STATEMENT:  EXECUTE registration (3,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 20:22:54.988 CET [15552] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.988 CET [20472] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.989 CET [9644] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.990 CET [21060] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.990 CET [16136] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.990 CET [23624] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.990 CET [21164] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.990 CET [18572] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.990 CET [16280] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.990 CET [8120] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.990 CET [23216] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.990 CET [14776] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.991 CET [17320] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.991 CET [8852] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.991 CET [10484] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:22:54.991 CET [2088] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:24:47.904 CET [25276] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:24:47.905 CET [21624] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:25:45.688 CET [5616] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:25:45.688 CET [2552] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:26:52.407 CET [13812] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:26:52.407 CET [8512] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:28:05.573 CET [14524] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:28:05.574 CET [7996] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:28:21.336 CET [8748] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:28:21.336 CET [12276] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:29:21.219 CET [11388] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:29:21.219 CET [17524] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:31:12.597 CET [16244] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:31:12.597 CET [24040] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:31:23.972 CET [24596] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 20:31:23.972 CET [24596] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 20:31:23.972 CET [24596] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 20:31:24.221 CET [24596] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 20:31:24.221 CET [24596] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 20:31:24.221 CET [24596] STATEMENT:  EXECUTE registration (3,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 20:34:11.868 CET [18624] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.868 CET [24596] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.869 CET [24856] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.871 CET [15268] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.871 CET [1296] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.871 CET [19944] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.871 CET [2280] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.871 CET [13528] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.871 CET [2124] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.871 CET [1556] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.872 CET [24500] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.872 CET [20904] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.872 CET [23720] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.872 CET [23356] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.872 CET [10212] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.872 CET [14656] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.872 CET [4988] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.872 CET [19784] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:34:11.872 CET [18404] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:35:54.890 CET [16416] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 20:35:54.890 CET [16416] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 20:35:54.890 CET [16416] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-21 20:35:55.136 CET [16416] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-21 20:35:55.136 CET [16416] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-21 20:35:55.136 CET [16416] STATEMENT:  EXECUTE registration (3,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-21 20:51:31.890 CET [16416] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.891 CET [16332] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.891 CET [2440] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.892 CET [21272] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.893 CET [12924] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.893 CET [20308] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.893 CET [1244] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.893 CET [14240] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.893 CET [14732] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.893 CET [8188] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.893 CET [17600] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.894 CET [14924] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.894 CET [10368] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.894 CET [19448] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.894 CET [25464] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.894 CET [10580] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.894 CET [19844] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:51:31.894 CET [21200] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:52:37.391 CET [24872] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:52:37.392 CET [13088] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:52:37.392 CET [23292] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:52:37.392 CET [7020] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 20:57:22.212 CET [11120] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 21:00:06.362 CET [19248] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 21:00:06.362 CET [13804] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 21:03:02.328 CET [19244] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 21:24:29.144 CET [18496] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-21 21:24:52.592 CET [12768] LOG:  server process (PID 2500) was terminated by exception 0xC000013A
2021-02-21 21:24:52.592 CET [12768] DETAIL:  Failed process was running: DELETE FROM users;
2021-02-21 21:24:52.592 CET [12768] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-02-21 21:24:52.592 CET [12768] LOG:  terminating any other active server processes
2021-02-21 21:24:52.593 CET [8584] WARNING:  terminating connection because of crash of another server process
2021-02-21 21:24:52.593 CET [8584] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-02-21 21:24:52.593 CET [8584] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-02-21 21:24:52.610 CET [12768] LOG:  all server processes terminated; reinitializing
2021-02-21 21:24:52.646 CET [12068] LOG:  database system was interrupted; last known up at 2021-02-21 21:04:13 CET
2021-02-21 21:24:52.925 CET [12068] LOG:  database system was not properly shut down; automatic recovery in progress
2021-02-21 21:24:52.928 CET [12068] LOG:  redo starts at 0/16E3190
2021-02-21 21:24:52.928 CET [12068] LOG:  invalid record length at 0/16E3270: wanted 24, got 0
2021-02-21 21:24:52.929 CET [12068] LOG:  redo done at 0/16E3238
2021-02-21 21:24:52.972 CET [12768] LOG:  database system is ready to accept connections
2021-02-21 21:25:03.582 CET [24936] ERROR:  canceling statement due to user request
2021-02-21 21:25:03.583 CET [24012] ERROR:  canceling statement due to user request
2021-02-21 21:25:03.583 CET [12768] LOG:  received fast shutdown request
2021-02-21 21:25:03.586 CET [12768] LOG:  aborting any active transactions
2021-02-21 21:25:03.595 CET [12768] LOG:  worker process: logical replication launcher (PID 24936) exited with exit code 1
2021-02-21 21:25:03.619 CET [19192] LOG:  shutting down
2021-02-21 21:25:03.641 CET [12768] LOG:  database system is shut down
2021-02-21 23:53:26.007 CET [14560] LOG:  listening on IPv6 address "::1", port 5432
2021-02-21 23:53:26.007 CET [14560] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-02-21 23:53:26.053 CET [23872] LOG:  database system was shut down at 2021-02-21 21:25:03 CET
2021-02-21 23:53:26.086 CET [14560] LOG:  database system is ready to accept connections
2021-02-22 00:35:20.959 CET [1852] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:30.562 CET [15780] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:52:30.562 CET [15780] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:52:30.562 CET [15780] STATEMENT:  EXECUTE registration (0,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-22 00:52:30.799 CET [15780] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:52:30.799 CET [15780] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:52:30.799 CET [15780] STATEMENT:  EXECUTE registration (0,'altenhof','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-22 00:52:31.023 CET [15780] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:52:31.023 CET [15780] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:52:31.023 CET [15780] STATEMENT:  EXECUTE registration (0,'admin','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-22 00:52:31.258 CET [15780] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:52:31.258 CET [15780] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:52:31.258 CET [15780] STATEMENT:  EXECUTE registration (0,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-22 00:52:31.502 CET [15780] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:52:31.502 CET [15780] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:52:31.502 CET [15780] STATEMENT:  EXECUTE registration (0,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-22 00:52:56.546 CET [15780] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.549 CET [16728] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.549 CET [24772] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.549 CET [25400] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.549 CET [6904] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.549 CET [13540] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.549 CET [12868] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.550 CET [21048] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.550 CET [10216] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.549 CET [9336] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.550 CET [10140] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.550 CET [8096] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.550 CET [25200] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.550 CET [21196] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.550 CET [14592] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.551 CET [17380] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.550 CET [19940] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:52:56.551 CET [24564] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:53:46.486 CET [16672] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:53:46.486 CET [16672] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:53:46.486 CET [16672] STATEMENT:  EXECUTE registration (0,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-22 00:53:46.715 CET [16672] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:53:46.715 CET [16672] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:53:46.715 CET [16672] STATEMENT:  EXECUTE registration (0,'altenhof','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-22 00:53:46.953 CET [16672] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:53:46.953 CET [16672] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:53:46.953 CET [16672] STATEMENT:  EXECUTE registration (0,'admin','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-22 00:53:47.181 CET [16672] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:53:47.181 CET [16672] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:53:47.181 CET [16672] STATEMENT:  EXECUTE registration (0,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-22 00:53:47.403 CET [16672] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:53:47.403 CET [16672] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:53:47.403 CET [16672] STATEMENT:  EXECUTE registration (0,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-22 00:53:52.224 CET [16672] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:53:52.224 CET [23448] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:53:52.224 CET [25436] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:53:52.224 CET [4528] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:53:52.224 CET [2700] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:53:52.224 CET [20932] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:53:52.224 CET [14696] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:55:20.619 CET [1992] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:55:20.619 CET [1992] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:55:20.619 CET [1992] STATEMENT:  EXECUTE registration (0,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-22 00:55:20.855 CET [1992] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:55:20.855 CET [1992] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:55:20.855 CET [1992] STATEMENT:  EXECUTE registration (0,'altenhof','24D9C7B19834AA278CE9609A00D156F61BD83184C2634D1C2B1D6AAA9C235B3A')
2021-02-22 00:55:21.079 CET [1992] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:55:21.079 CET [1992] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:55:21.079 CET [1992] STATEMENT:  EXECUTE registration (0,'admin','175490A3844460FE5B3D03B2879863A81F812C7566165E16673FA96F0B0C5BD8')
2021-02-22 00:55:21.299 CET [1992] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:55:21.299 CET [1992] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:55:21.299 CET [1992] STATEMENT:  EXECUTE registration (0,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-22 00:55:21.525 CET [1992] ERROR:  duplicate key value violates unique constraint "users_pkey"
2021-02-22 00:55:21.525 CET [1992] DETAIL:  Key (userid)=(0) already exists.
2021-02-22 00:55:21.525 CET [1992] STATEMENT:  EXECUTE registration (0,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-22 00:55:41.654 CET [1992] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:55:41.655 CET [20804] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:55:41.655 CET [25152] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:55:41.655 CET [23696] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:55:41.655 CET [23052] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:55:41.655 CET [8872] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:55:41.655 CET [11592] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:55:41.655 CET [12420] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:55:41.656 CET [16688] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:55:41.656 CET [15992] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:55:41.657 CET [22472] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:55:41.657 CET [7212] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 00:56:19.563 CET [20768] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-22 00:56:19.563 CET [20768] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-22 00:56:19.563 CET [20768] STATEMENT:  EXECUTE registration (3,'kienboec','BD3DAE5FB91F88A4F0978222DFD58F59A124257CB081486387CBAE9DF11FB879')
2021-02-22 00:56:19.793 CET [20768] ERROR:  duplicate key value violates unique constraint "users_login_key"
2021-02-22 00:56:19.793 CET [20768] DETAIL:  Key (login)=(kienboec) already exists.
2021-02-22 00:56:19.793 CET [20768] STATEMENT:  EXECUTE registration (3,'kienboec','9D6F965AC832E40A5DF6C06AFE983E3B449C07B843FF51CE76204DE05C690D11')
2021-02-22 01:18:50.418 CET [20768] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.419 CET [19596] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.419 CET [14724] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.420 CET [21016] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.420 CET [17228] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.420 CET [24476] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.420 CET [24996] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.421 CET [23560] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.421 CET [18148] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.421 CET [15704] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.421 CET [9444] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.421 CET [25220] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.422 CET [23124] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.422 CET [13940] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.422 CET [12716] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.422 CET [16756] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.422 CET [12452] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:18:50.422 CET [23888] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:20:30.054 CET [21384] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
2021-02-22 01:20:36.300 CET [14560] LOG:  server process (PID 9940) was terminated by exception 0xC000013A
2021-02-22 01:20:36.300 CET [14560] DETAIL:  Failed process was running: SELECT * FROM users;
2021-02-22 01:20:36.300 CET [14560] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-02-22 01:20:36.300 CET [14560] LOG:  terminating any other active server processes
2021-02-22 01:20:36.301 CET [9416] WARNING:  terminating connection because of crash of another server process
2021-02-22 01:20:36.301 CET [9416] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-02-22 01:20:36.301 CET [9416] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-02-22 01:20:36.333 CET [14560] LOG:  all server processes terminated; reinitializing
2021-02-22 01:20:36.371 CET [19092] LOG:  database system was interrupted; last known up at 2021-02-22 00:58:27 CET
2021-02-22 01:20:36.819 CET [19092] LOG:  database system was not properly shut down; automatic recovery in progress
2021-02-22 01:20:36.822 CET [19092] LOG:  redo starts at 0/16EC388
2021-02-22 01:20:36.822 CET [19092] LOG:  invalid record length at 0/16EC468: wanted 24, got 0
2021-02-22 01:20:36.822 CET [19092] LOG:  redo done at 0/16EC430
2021-02-22 01:20:36.856 CET [14560] LOG:  database system is ready to accept connections
2021-02-22 01:20:44.653 CET [12084] ERROR:  canceling statement due to user request
2021-02-22 01:20:44.654 CET [24148] ERROR:  canceling statement due to user request
2021-02-22 01:20:44.654 CET [14560] LOG:  received fast shutdown request
2021-02-22 01:20:44.660 CET [14560] LOG:  aborting any active transactions
2021-02-22 01:20:44.665 CET [14560] LOG:  worker process: logical replication launcher (PID 12084) exited with exit code 1
2021-02-22 01:20:44.689 CET [17872] LOG:  shutting down
2021-02-22 01:20:44.734 CET [14560] LOG:  database system is shut down
